apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-execution-remote-code-exec-in-container
  namespace: multiubuntu
spec:
  selector:
      matchLabels:
          container: ubuntu-5
  process:
    matchPaths: 
    - path: /usr/bin/nc
    - path: /usr/bin/ncat
  action:
    Audit
  severity: 6
