apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-defense-evasion-system-log
  namespace: multiubuntu
spec:
  tags: ["MITRE", "Defense Evasion"]
  selector:
      matchLabels:
          container: ubuntu-5 
  file:
    matchDirectories:
    - dir: /var/log/
      recursive: true
      readOnly: true

  action:
    Block
  severity: 5
